/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafarisRouteImport } from './routes/safaris'
import { Route as IndexRouteImport } from './routes/index'

const SafarisRoute = SafarisRouteImport.update({
  id: '/safaris',
  path: '/safaris',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/safaris': typeof SafarisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/safaris': typeof SafarisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/safaris': typeof SafarisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/safaris'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/safaris'
  id: '__root__' | '/' | '/safaris'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SafarisRoute: typeof SafarisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safaris': {
      id: '/safaris'
      path: '/safaris'
      fullPath: '/safaris'
      preLoaderRoute: typeof SafarisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SafarisRoute: SafarisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
